monitoring:
  port: 8080
  address: localhost
  requestTimeoutSeconds: 25

celoNodeURI: ws://localhost:8546
sensitiveAccountsFilePath: ~/sensitiveAccounts.json
profiling: true

redis:
  address: localhost:6379
  password: ""
  db: 5

publisher:
  backfill: 
    enabled: true
    startBlock: 0
    batchSize: 100
    sleepIntervalSeconds: 2
  chainFollower:
    enabled: false

indexer:
  sleepIntervalMilliseconds: 100
  workers: 3
  workerNodeURIs:
    - "http://localhost:6545"
    - "http://localhost:6545"
    - "http://localhost:6545"
  

